import { File } from "@asyncapi/generator-react-sdk";
import ejs from "ejs";

const resource = `
# This file was generated by asyncapi-generator.
# Any changes will be overwritten.

apiVersion: neuron.isf/v1alpha1
kind: NeuronTopic
metadata:
  name: <%= topicName %>
spec:
  tenant: <%= tenantName %>
  namespace: <%= namespaceName %>
  topic: <%= topicName %>
`;

export function renderTopics({ asyncapi }) {
  const topics = fetchTopics(asyncapi._json.channels);

  return topics.map(({ topic, namespace, tenant }) => {
    const filename = `${topic}-topic.yaml`;
    const env = {
      topicName: topic,
      namespaceName: namespace,
      tenantName: tenant,
    };

    return <File name={filename}>{ejs.render(resource, env).trim()}</File>;
  });
}

function fetchTopics(channels) {
  const topics = new Set();

  for (const channel in channels) {
    if (typeof channel === "string") {
      const parts = channel.split("/");
      const tenant = parts[0];
      const namespace = parts[1];
      const topic = parts[2];

      topics.add({ topic, namespace, tenant });
    }
  }

  return [...topics];
}
