import { File } from "@asyncapi/generator-react-sdk";
import ejs from "ejs";
import {
  renderTenants,
  renderNamespaces,
  renderTopics,
  renderSchemas,
} from "../../components/all";

const resource = `
# This file was generated by asyncapi-generator.
# Any changes will be overwritten.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - <%= files.join("\\n  - ") %>
`;

export default function ({ asyncapi }) {
  const output = [
    renderTenants({ asyncapi }),
    renderNamespaces({ asyncapi }),
    renderTopics({ asyncapi }),
    renderSchemas({ asyncapi }),
  ].flat(1);

  const files = new Set();
  for (const f of output) {
    if (f.props && typeof f.props.name === "string") {
      files.add(f.props.name);
    }
  }

  return [
    ...output,
    <File name="kustomization.yaml">
      {ejs.render(resource, { files: [...files] }).trim()}
    </File>,
  ];
}
