on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.code.rbi.tech
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        shell: bash
        run: |
          docker build -t docker.code.rbi.tech/${{github.repository}}/action:${{github.ref_name}} .

      - name: push docker image
        shell: bash
        run: |
          docker push docker.code.rbi.tech/${{github.repository}}/action:${{github.ref_name}}
